dependency_support: bump bazel_rules_hdl
google/xls pull request #1230
Opened 2023-12-15 10:51 UTC by lpawelcz

This PR includes fixes for https://github.com/google/xls/pull/1031:

* improve hermetic python handling
* remove cpython and embedded_python_interpreter

Additionally, the bumped version of `bazel_rules_hdl` include work related to improving bazel place_and_route flow (https://github.com/hdl/bazel_rules_hdl/issues/239) and benchmarking experience (https://github.com/google/xls/issues/1226)

CC @proppy

2023-12-15 15:12 UTC, ericastor requested changes

2023-12-15 15:12 UTC, ericastor commented on dependency_support/rules_hdl/workspace.bzl
>      # Current as of 2023-12-05
Please update this date!

2023-12-18 08:58 UTC, lpawelcz commented on dependency_support/rules_hdl/workspace.bzl
>      # Current as of 2023-12-05
Right, thanks for pointing that out.

2023-12-18 08:58 UTC, lpawelcz commented
There are some pending PRs in `bazel_rules_hdl` which are related to `place_and_route` flow and design benchmarking that should be merged in the nearest future, e.g.:
* https://github.com/hdl/bazel_rules_hdl/pull/247
* changes from https://github.com/hdl/bazel_rules_hdl/pull/243 split into a batch of small PRs based on [upstreaming plan](https://github.com/hdl/bazel_rules_hdl/pull/243#pullrequestreview-1781000193)

We could wait for these to get merged and then bump this PR to include all changes or merge as it is now and open another PR with next update once `bazel_rules_hdl` PRs are merged.

2023-12-21 08:08 UTC, lpawelcz commented
@proppy all recent PRs with improvements to place and route rules in `bazel_rules_hdl` are merged. I've bumped our `bazel_rules_hdl` dependency to include those.

2023-12-21 08:35 UTC, proppy approved these changes

2023-12-21 10:53 UTC, merged